
# Project information
site_name: nRF52840 MDK USB Dongle
site_description: nRF52840 Micro Development Kit (USB Dongle Form Factor)
site_author: makerdiary
site_url: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/

# Repository
repo_name: nrf52840-mdk-usb-dongle
repo_url: https://github.com/makerdiary/nrf52840-mdk-usb-dongle
edit_uri: "https://github.com/makerdiary/nrf52840-mdk-usb-dongle/docs"

# Copyright
copyright: 'Copyright &copy; 2019 <a href="https://makerdiary.com">makerdiary.com</a>'

# Configuration
theme:
  name: null
  custom_dir: 'mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: red-bud
    accent: red-bud
  font:
    text: Roboto
    code: Roboto Mono
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/logo.svg'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: comments
      link: https://community.makerdiary.com
    - type: globe
      link: https://makerdiary.com
    - type: github-alt
      link: https://github.com/makerdiary
    - type: twitter
      link: https://twitter.com/makerdiary
#  disqus: 'makerdiary'
#  discourse: 'community.makerdiary.com'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: makerdiary
      repo: nrf52840-mdk-usb-dongle
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Programming: programming.md
  - nRF5 SDK: nrf5-sdk.md
  - OpenThread Border Router: OTBR.md
  - Thread Network Sniffer: thread-sniffer.md
  - OpenSK:
    - Overview: opensk/index.md
    - Getting Started: opensk/getting-started.md
    - How to build OpenSK: opensk/building.md
  - How to Buy: how-to-buy.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
 

# Google Analytics
google_analytics:
  - 'UA-54344624-2'
  - 'auto'
